name: ${project.name}
version: ${project.version}
author: totemo
authors: []
description: ${project.description}
website: ${project.url}
main: nu.nerd.perf.NerdPerf

permissions:
  nerdperf.admin:
    description: Permission to administer the plugin.
    default: op

  nerdperf.lag:
    description: Permission to run the /lag command.
    default: op

commands:
  nerdperf:
    description: ${project.name} administrative command.
    permission: nerdperf.admin
    usage: |
    
      §e/<command> reload§f - Reload the configuration.

  lag:
    description: Show the current TPS and memory usage.
    permission: nerdperf.lag
    usage: |
    
      §e/<command>§f - Show the current TPS and memory usage.
